import type { Metadata } from "next";
import { Footer } from "./components/footer/Footer";
import "./globals.css";
import "./Variables.css";

export const metadata: Metadata = {
  title: "Douglas Lyman - Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col">
        {children}
        <Footer/>
      </body>
    </html>
  );
}
